blog:
  site: chaopeng.github.com
  path: /blog
  author: ChaoPeng
  blogname: 巢鹏的Pensieve
  # set the markdown engine which you like
  markdownengine: python3 -m markdown -x toc -x footnotes -x fenced_code -x tables
  inputpath: /data/chao/workspace/chaosblog/to-be-publish
  outputpath: /data/chao/workspace/chaosblog/published

author:
  mail: chaopeng@chaopeng.me
  gravatar: chaopeng@chaopeng.me
  gravatarserver: https://secure.gravatar.com
  weibo: http://weibo.com/chaojianpeng
  github: https://github.com/chaopeng
  wechat: Xszl-ULEKx9UrQae95lM