blog:
  site: chaopeng.me
  path: /blog
  author: ChaoPeng
  blogname: 巢鹏的Pensieve
  # set the markdown engine which you like
  markdownengine: python3 -m markdown -x toc -x footnotes -x fenced_code -x tables
  inputpath: /home/chao/blog/to-be-publish
  outputpath: /home/chao/blog/chaopeng.github.com

author:
  mail: chaojianpeng@gmail.com
  gravatar: chaopeng@chaopeng.me
  gravatarserver: https://secure.gravatar.com
  weibo: http://weibo.com/chaojianpeng
  github: https://github.com/chaopeng
  wechat: Xszl-ULEKx9UrQae95lM
